build:
  environment:
    php: 7.2.0
    redis: true
  nodes:
    analysis:
      project_setup:
        override:
        - 'true'
      tests:
        override:
        - command: cp .env.scrutinizer .env
        - command: composer self-update
        - command: composer install --prefer-source --no-interaction --dev
        - command: php artisan key:generate
        - command: php artisan route:list
        - php-scrutinizer-run
filter:
  paths:
  - 'app/*'
  - 'config/*'
  excluded_paths:
  - 'vendor/*'
  - 'public/*'
  - 'storage/*'
  - 'bootstrap/*'
  - 'config/*'
  - 'node_modules/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      within:
        brackets: true