dist: xenial

language: php
php:
- 7.2

sudo: true

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp .env.travis .env
- php artisan key:generate
- composer self-update
- composer install --prefer-source --no-interaction --dev
- php artisan migrate
- php artisan route:list
- nvm install node
- npm install npm@latest -g
- npm install
- npm run production

script:
- phpunit

services:
- postgresql

addons:
  postgresql: "10"